# kubernetes/backstage.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: gcr.io/mokeefe-test-6/backstage:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: LOG_LEVEL
              value: debug
          envFrom:
            - secretRef:
                name: postgres-secrets
            - secretRef:
                name: github-secret
            - secretRef:
                name: google-oauth-secret
